### ISSUE TITLE
It's just not working

### ISSUE THREAD

**Issue by Puggetty** [endercrest/VoidSpawn#45]
Hello
I may have goofed up somewhere but I can't seem to get this plugin to work. I jump into the void and I just keep falling?
Here is my "worlds" config file:
```
empty:
  spawn:
    x: 0.5122707072066655
    y: 29.0
    z: 0.5921793643041521
    pitch: 68.76303
    yaw: -2.0989985
    world: Empty
  mode: spawn
  keep_inventory: true

```
I'm also running PaperSpigot.
Any suggestions?
Thanks!
