### ISSUE TITLE
Feature requests: Augment bounce capabilities

### ISSUE THREAD

**Issue by SlimeDog** [endercrest/VoidSpawn#86]
Thanks for the update. Nice to see that you're still around.

Tested VoidSpawn 1.19.3 on Paper 1.16.5-730.

In-game in the world of interest, executed
```
/vs option set bounce 15
```

`worlds.yml` now looks like this
```
world_skyblock:
  mode: touch
  options:
    message: Where were you going? Count that as a death!
    hybrid: true
    command: op:stats ${player.name} DEATHS ++1;op:bsbadmin deaths add ${player.name}
      1;op:mvtp ${player.name} e:world_void:0.5,64,0.1:0:0
    bounce: '15'
```

The bounce is very good. Several items of note:
- Bounce is not listed by the `info` subcommand.
- In the test case (BSkyBlock), the fall was 127 meters. The height of the bounce appears to be approximately 22 meters. It would be nice to be able to specify the height. By default, it should be the height of the fall (plus a meter or two?) if that can be captured. Otherwise, it would be nice to have an option to set the height -- that is, the Y-coordinate at the top of the bounce (assuming that the bottom is Y=0).
- Extra credit: It would be nice to be able to configure repeated bounces as a decreasing percentage of the height. So the first bounce is the full height, the next is slightly shorter, the next shorter still, etc.
- Bounce is reported in-game for each second of bounce. I am not sure what is being reported, and in any event, I would like it to be silent -- at least, as an option.
```
Bounce!0.0,2.9860210961020428,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
Bounce!0.0,2.0,0.0
```
